question_data = [{"type": "boolean", "difficulty": "easy", "category": "Animals",
                  "question": "Rabbits can see what&#039;s behind themselves without turning their heads.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "General Knowledge",
                  "question": "March 10th is also known as Mar10 Day.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Television",
                  "question": "In the Season 1 SpongeBob Squarepants episode, &quot;Help Wanted,&quot; the song &quot;Living in the Sunlight&quot; by Tiny Tim can be heard.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Music",
                  "question": "Daft Punk originated in France.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard",
                  "category": "Entertainment: Video Games",
                  "question": "In &quot;The Sims&quot; series, the most members in a household you can have is 8.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Animals",
                  "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "The capital of the US State Ohio is the city of Chillicothe.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "Kissing someone for one minute burns about 2 calories.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Science &amp; Nature",
                  "question": "Salt is 100% composed of Sodium.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Music",
                  "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
